pipeline {
 agent none
 options {  
     timeout(time: 10, unit: 'MINUTES') 
 }
 
 stages
 {
  stage('Checkout')
  {
  agent { label 'test' }
   steps { 
    git branch: 'master', url: 'https://github.com/Devopsmural/CICD.git'
   }
  }
  stage('Code Coverage')
 {
 agent { label'test' }
   when {
    expression { return params.CODEANAYLSIS }
  }
  steps {
   echo "Running Code Coverage ..."
    dir ("./samplejar") {
     sh'mvn org.jacaco
      }
    }
 }
 }
}
