pipeline {
 agent none
 options {  
     timeout(time: 10, unit: 'MINUTES') 
 }
 
 stages
 {
  stage('Checkout')
  {
  agent { label 'test' }
   steps { 
    git branch: 'master', url: 'https://gitlab.com/https://github.com/Devopsmural/CICD.git'
   }
  }
  
  stage('Build Artifacts')
  {
   agent { label 'test' }
   steps { 
        dir ("./CICD/samplejar") {
           sh "mvn clean package "
		}
		dir ("./CICD/samplewar") {
           sh "mvn clean package "
		}
   }
  }
